language: node_js
node_js:
    - '7'
cache:
    directories:
        - node_modules
script:
    - npm install codecov -g
    - npm install
    - npm test
    - npm start
after_success:
    - npm run coverage
